Add app and main files
Bigizi/OOP-school-library pull request #4
Opened 2023-04-21 10:21 UTC by Bigizi

**oop-school-project**

- Creating the app.rb file that will serve as console app entry-point
- Creating the main.rb file that defines the entry point

2023-04-21 10:55 UTC, brytebee requested changes
Hi, @Bigizi👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- App functions as it should.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 10:55 UTC, brytebee commented on app.rb
> +  end
The create student function throws this error. kindly fix it.

![image](https://user-images.githubusercontent.com/27709832/233618379-b5547b39-a60c-4387-a493-8f6c02bb8746.png)

2023-04-21 10:55 UTC, brytebee commented on app.rb
> +  end
The create_teacher function throws the error below. Kindly fix it.

![image](https://user-images.githubusercontent.com/27709832/233619022-25670023-fd41-4698-b34b-453f9843e9b3.png)

2023-04-21 10:56 UTC, brytebee commented
Moreso, Kindly confirm that every other resource can be created seamlessly. Thanks.

2023-04-22 08:14 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @Bigizi 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-04-22 08:55 UTC, merged