Preserve data
Bigizi/OOP-school-library pull request #7
Opened 2023-04-26 19:35 UTC by Bigizi

**Oop school library project**

This group is made by @Bigizi, @Habtamu210, and @alicemirigo92.
this app saves all the data (books, people, and rentals) into JSON files. One per type of data you are storing and named accordingly (e.g. rentals.json)

2023-04-26 20:09 UTC, danmainah requested changes
Hi @Bigizi , @Habtamu210 and @alicemirigo92 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-26 20:09 UTC, danmainah commented on README.md
- [ ] @team great work on your documentation, however, the MIT license link is not working, 
![image](https://user-images.githubusercontent.com/61408860/234689188-80aafc7d-6d68-4964-a2cd-5e6f80acd343.png)

2023-04-26 20:09 UTC, danmainah commented on Module/rental_options.rb
> +    end
- [ ] @team great work on your RentalOptions class methods, however when I save a rental am unable to view it, kindly check on your output for the rentals 
![image](https://user-images.githubusercontent.com/61408860/234690578-cecc7333-cf14-471c-8bd5-89fad6be12a9.png)

2023-04-27 07:37 UTC, sumairq approved these changes
### Hi Team, 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 07:40 UTC, merged